// <auto-generated />
using MarthaPadilhaLeiloes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarthaPadilhaLeiloes.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("MarthaPadilhaLeiloes.Model.Comitente", b =>
                {
                    b.Property<int>("ComitenteId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ComitenteName");

                    b.HasKey("ComitenteId");

                    b.ToTable("Comitentes");
                });
#pragma warning restore 612, 618
        }
    }
}
